### ISSUE TITLE
[Request] Add "Hide on toolbar" option.

### ISSUE THREAD

**Issue by ZeiZeiii** [NathanQuayle/max-skill-trim#1]

**Comment by NathanQuayle** [comment]
Hey, thanks for feedback.

When you say toolbar, what do you mean? Can you attach a screenshot?

**Comment by ZeiZeiii** [comment]
I mean the Runelite sidebar on the right. Ability to hide plugin's icon, Im very happy for the default trim so I have no need to have quick access.

Feb 3, 2023, 21:40 by ***@***.***:

**Comment by NathanQuayle** [comment]
I'm pushing up the change for this now. Not sure how long it takes to go through Runelite's approval process, but it should be available soon. Will close this when it's live. :)

**Comment by NathanQuayle** [comment]
This should be live now. If you get any issues, feel free to re-open.

Thanks again for the suggestion. :)

**Comment by ZeiZeiii** [comment]
Thank you sir! :) Any chance to get you fix this as well? :p
![image](https://user-images.githubusercontent.com/123414249/216814826-5a567bcd-ad9f-42f8-a14b-6ecb37398d93.png)

**Comment by NathanQuayle** [comment]
Ooh, will take a look into this. I thought I had solved this! Thank you!
