### ISSUE TITLE
[Bug] Make Mouse-Over text appear in front of trim

### ISSUE THREAD

**Issue by Nick2bad4u** [NathanQuayle/max-skill-trim#2]
![image](https://user-images.githubusercontent.com/20943337/221735682-9e9c62d3-0e64-48be-b58c-c84e7f1b4216.png)

As shown above.

**Comment by NathanQuayle** [comment]
Hey Nick, thanks for the report. I'll try to find some time this weekend to look at this.

**Comment by NathanQuayle** [comment]
Will try to get this up ASAP, but should be resolved on next release. :)

**Comment by Nick2bad4u** [comment]
> Will try to get this up ASAP, but should be resolved on next release. :) 

Beautiful.
