### ISSUE TITLE
[Custom Trims] Custom Trims I made for anyone to use

### ISSUE THREAD

**Issue by Nick2bad4u** [NathanQuayle/max-skill-trim#3]
![red-blue](https://user-images.githubusercontent.com/20943337/222792187-5384255a-7ce4-44a6-9ead-5fcd9463b6cd.png)
![pink-peach-orange](https://user-images.githubusercontent.com/20943337/222792191-24673a8f-0709-45dd-96de-496ccfa8e4ef.png)
![red-pink-purple](https://user-images.githubusercontent.com/20943337/222792192-2e2bf0f8-42e4-45a1-905e-d9494d6999c0.png)
![purple-blue-lightpurple](https://user-images.githubusercontent.com/20943337/222792194-c58a8396-b270-49b5-b276-f1061568d2fa.png)
![yellow-green-blue](https://user-images.githubusercontent.com/20943337/222792195-f7f73d64-9aeb-478d-9a22-77c18b2f4de3.png)
![red-green-blue](https://user-images.githubusercontent.com/20943337/222792196-631a2b64-0a4c-4e48-a93d-09fbfeab0f6d.png)
![orange-blue](https://user-images.githubusercontent.com/20943337/222792197-c89e7d0b-3926-46fe-b774-a0df5a6a7ea3.png)
![pink-green](https://user-images.githubusercontent.com/20943337/222792198-4ea477de-8b46-468a-a5b2-9499dd2bddfa.png)
![yellow-green](https://user-images.githubusercontent.com/20943337/222792199-d8a4b58a-f296-4c61-b132-382bae0e974e.png)
![pink-blue](https://user-images.githubusercontent.com/20943337/222792200-3a9b6441-d632-428f-8a57-81a80ccf2f21.png)

Batch 2:

![dark-red-dark-green](https://user-images.githubusercontent.com/20943337/224570338-6d5ff0d9-0302-4f3d-a538-72c876026f45.png)
![ice-light-purple](https://user-images.githubusercontent.com/20943337/224570339-737f3f37-61fb-438f-944e-79ffb319a77d.png)
![orange-cream](https://user-images.githubusercontent.com/20943337/224570340-339bb8d8-64a8-4389-b480-aceb250e6d96.png)
![rainbow3](https://user-images.githubusercontent.com/20943337/224570342-e0706e03-fd3f-4ef7-8155-749cb8806984.png)
![rainbow2](https://user-images.githubusercontent.com/20943337/224570343-9a53d686-1e85-46c7-88de-e149046f3513.png)
![rainbow1](https://user-images.githubusercontent.com/20943337/224570344-af8d04f2-32bd-4616-9254-677c5fe0f1a9.png)
![purple-orange-halloween](https://user-images.githubusercontent.com/20943337/224570345-5d568fa6-5cd6-4a7f-90b4-04cd638fbb71.png)
![blue-green-alternating](https://user-images.githubusercontent.com/20943337/224570346-03c0ad97-ee4a-42a4-8d2d-0e2edbed6771.png)
![purple-alternating](https://user-images.githubusercontent.com/20943337/224570347-b3255c27-dd48-420d-bff0-8caed6e1948f.png)
![multicolor-pinks](https://user-images.githubusercontent.com/20943337/224570348-f642f3a4-f718-465c-94e3-6c98e4f6e8a1.png)
![multicolor-purple](https://user-images.githubusercontent.com/20943337/224570349-980e74cc-082a-473e-9ecc-899baa368334.png)
![tan-pink](https://user-images.githubusercontent.com/20943337/224570350-be576283-64e0-4c88-aaa0-e24e258d6dcf.png)
![red-green-blue-pastel](https://user-images.githubusercontent.com/20943337/224570351-3d5f8663-6b01-4080-a19f-d32f68e74502.png)
![pink-purples-light-blue-alternating](https://user-images.githubusercontent.com/20943337/224570352-570237d3-f709-4b64-9b49-1220951fba81.png)
![light-green-pink](https://user-images.githubusercontent.com/20943337/224570353-988d2967-4b59-4fd6-ad77-c133e269afd4.png)
![purple-pink-alternating](https://user-images.githubusercontent.com/20943337/224570354-48034ea8-e82e-4c30-9580-40677da7dce9.png)
![blue-pink-purple](https://user-images.githubusercontent.com/20943337/224570355-e72238fe-4e95-46f8-aaa7-c53f7624afd1.png)
![summer-wave](https://user-images.githubusercontent.com/20943337/224570356-de937760-8d97-4973-a8eb-76904589f16d.png)

Feel free to download and use

Edit: will add to this list as I make more

**Comment by Nick2bad4u** [comment]
@NathanQuayle Feel free to include any of these in the defaults that you want.

**Comment by NathanQuayle** [comment]
I love these! Great job 👍 . I'll try to find some time this weekend to move them to https://github.com/NathanQuayle/max-skill-trim/tree/custom-trims :)

**Comment by NathanQuayle** [comment]
Hey Nick, gonna close this. You can now see all the trims at: https://nathanquayle.github.io/max-skill-trim/.

I've marked them all as 'Designed by anonymous' because I wasn't sure if you wanted your username there. But if you do feel free to move them into a folder with whatever display name you'd like and it'll be picked up.

**Comment by Nick2bad4u** [comment]
> Hey Nick, gonna close this. You can now see all the trims at: https://nathanquayle.github.io/max-skill-trim/.
> 
> I've marked them all as 'Designed by anonymous' because I wasn't sure if you wanted your username there. But if you do feel free to move them into a folder with whatever display name you'd like and it'll be picked up.

Awesome!!
