### ISSUE TITLE
Plugin Unavailable?

### ISSUE THREAD

**Issue by ZeiiKz** [NathanQuayle/max-skill-trim#4]
Hi, is this plugin still available? 

It has disappeared from the client & plugin hub.

**Comment by NathanQuayle** [comment]
Hey ZeiiKz,

There awas a recent breaking change in Runelite.

I’ve submitted a fix which can be tracked here:
https://github.com/runelite/plugin-hub/pull/4058

It’s unfortunately still pending approval by the Runelite team and I don’t
think I’m allowed to chase the devs up for approval, so I’m not sure how
long it will take.

**Comment by NathanQuayle** [comment]
Hey ZeiiKz,

There awas a recent breaking change in Runelite.

I’ve submitted a fix which can be tracked here: 
https://github.com/runelite/plugin-hub/pull/4058

It’s unfortunately still pending approval by the Runelite team and I don’t think I’m allowed to chase the devs up for approval, so I’m not sure how long it will take.
