### ISSUE TITLE
[Bug] Settings inaccessible

### ISSUE THREAD

**Issue by Nick2bad4u** [NathanQuayle/max-skill-trim#5]
Unable to find settings in the settings panel or in the plugin hub
![image](https://user-images.githubusercontent.com/20943337/226080695-99c8f037-c2c9-497b-85cd-a24fce57fac7.png)
![image](https://user-images.githubusercontent.com/20943337/226080709-3af79d7f-2eb8-47a9-a4b8-fb52475a3164.png)
![image](https://user-images.githubusercontent.com/20943337/226080715-598884e7-3d61-4fa7-b79d-19b6d8f2d0f8.png)

**Comment by NathanQuayle** [comment]
I'm unable to replicate this

I just uninstalled & reinstalled and it worked fine. 

Have you tried restarting your client / removing the plugin? It was unavailable earlier - but I can see the ID is the newest version.

**Comment by Nick2bad4u** [comment]
> I'm unable to replicate this
> 
> I just uninstalled & reinstalled and it worked fine.
> 
> Have you tried restarting your client / removing the plugin? It was unavailable earlier - but I can see the ID in your screenshot is the newest version.

I rebooted and its fixed. also the bug from before w/ the text is fixed!!! ty!

**Comment by NathanQuayle** [comment]
I'm glad to hear it's resolved! 😄👍
