### ISSUE TITLE
"Show nav button" setting ignored on startup

### ISSUE THREAD

**Issue by taximadish** [NathanQuayle/max-skill-trim#6]
Even if you have "Show navigation button in sidebar" unticked, the nav button will still appear when you next boot up the game.
I assume `MaxSkillTrimPlugin.startUp()` just needs an `if(showNavButton)` condition when it creates the nav button.

Love this plugin by the way, thanks for making it :)

**Comment by NathanQuayle** [comment]
Hey, thank you for the kind comments! :)

You're 100% right about it needing an `if` in `startUp`! Good catch. Will get a PR in for this in a min. 👍

**Comment by NathanQuayle** [comment]
This should be resolved now. If it's still an issue, let me know and I'll take another look. Thanks again 😀
